name: Checkers
on: [push]
jobs:
  lint:
    name: Black code formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.12

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with test

      - name: Run pytest and coverage
        run: poetry run python -m pytest -v --cov=app/ tests/

      - name: Run pytest and coverage
        run: poetry run python -m pytest -v --cov=app/ tests/